parameters:
#    webb_user.example.class: Webb\UserBundle\Example

services:
#    webb_user.example:
#        class: %webb_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
