webb_post_note_create:
    pattern:  /stf{fleet}/{ship}/note/create
    defaults: { _controller: WebbPostBundle:Note:create }

webb_post_note_view:
    pattern:  /stf{fleet}/{ship}/note/{id}
    defaults: { _controller: WebbPostBundle:Note:show }


webb_post_note_edit:
      pattern:  /stf{fleet}/{ship}/note/{id}/edit
      defaults: { _controller: WebbPostBundle:Note:edit }

