webb_character_create:
    pattern:  /character/create
    defaults: { _controller: WebbCharacterBundle:Persona:create }

webb_character_view:
    pattern:  /character/{id}
    defaults: { _controller: WebbCharacterBundle:Persona:show }
    requirements:
        page:  \d+

webb_character_edit:
      pattern:  /character/{id}/edit
      defaults: { _controller: WebbCharacterBundle:Persona:edit }
      requirements:
          page:  \d+
